import Link from 'next/link'

export const metadata = {
  title: 'Sistema Olá mundo!',
  description: 'Generated by Sistema Olá mundo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <h1>Sistema: Olá mundo!</h1>
        <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/users">Usuários</Link></li>
            <li><Link href="/login">Login</Link></li>
          </ul>
        </nav>
        <hr />

        {children}</body>
    </html>
  )
}
